name: timezone
version: 0.6.1
authors:
- Boris Kaul <localvoid@gmail.com>
- Sam Rawlins <sam.rawlins@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  path: '^1.3.0'
dev_dependencies:
  args: any
  glob: any
  logging: any
  test: any
